
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot-reloading
      - .:/app
    environment:
      # These variables would be loaded from .env file in a real scenario
      - APP_SERVER_MODE=debug
      - DB_DRIVER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go_vibe_friend
      - DB_SSLMODE=disable
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Pass through from host
    depends_on:
      - db
    # The command can be overridden to use a hot-reload tool like Air
    # command: air -c .air.toml

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_vibe_friend
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
